apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: bookstores.srinath.com
spec:
  group: srinath.com
  names:
    kind: BookStore
    listKind: BookStoreList
    plural: bookstores
    singular: bookstore
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true